version: '3'
services:

    containerizando:
        image: rmnobarra/containerizando
        environment:
          DATABASE_URL: "jdbc:postgresql://poscontainerizandotgres:5432/db"
        depends_on:
          - "postgres"
        ports:
          - 8080:8080    

    postgres:
        image: 'postgres:alpine'
        volumes:
          - postgres-volume:/var/lib/postgresql/data
        ports:
          - 5432:5432
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
          POSTGRES_HOST: postgres    
volumes:
  postgres-volume: