version: 0.2

phases:
  install:
    commands:
      - curl -o /bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/linux/amd64/kubectl
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
      - wget -qO- https://get.helm.sh/helm-v3.5.2-linux-amd64.tar.gz | tar xvz
      - mv linux-amd64/helm /bin/helm
      - chmod +x /bin/kubectl /bin/helm ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - apt-get update && apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli

  pre_build:
    commands:
      - docker login -u AWS -p $(aws ecr-public get-login-password --region us-east-1) $URL_REPO
      - sh gradlew build -x test
      - echo exporting kubeconfig
      - export KUBECONFIG=$HOME/.kube/config
      
  build:
    commands:
      - ./mvnw package
      - docker build -t containerizando . 
      - docker tag containerizando:latest public.ecr.aws/i2c7a5l2/lab/containerizando:latest

  post_build:
    commands:
      - docker login -u AWS -p $(aws ecr-public get-login-password --region us-east-1) public.ecr.aws/i2c7a5l2/lab
      - docker push public.ecr.aws/i2c7a5l2/lab/containerizando:latest
      - helm lint pipeline/helm/containerizando --values pipeline/helm/containerizando/values.yaml
      - aws eks update-kubeconfig --name zup-sandbox-edu-lab --role-arn arn:aws:iam::208471844409:role/CodeBuildKubectlRole
      - helm upgrade -i containerizando pipeline/helm/containerizando/ --values pipeline/helm/containerizando/values.yaml