helmDefaults:
  tillerless: true
  verify: false
  wait: true
  timeout: 600
  force: true
  
helmBinary: /usr/local/sbin/helm

releases:
  - name: containerizando
    chart: ./containerizando
    namespace: default
    values:
    - ./containerizando/values.yaml
    recreatePods: true
    set:
    - name: application.DATABASE_USER
      value: {{ requiredEnv "DB_USER" }}
    - name: application.DATABASE_URL
      value: {{ requiredEnv "DB_URL" }}
    - name: application.DATABASE_PASS
      value: {{ requiredEnv "DB_PASS" }}

